In [56]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding,LSTM,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [57]:
data = """Ex Wife Threatening Suicide Recently I left my wife for good because she has cheated on me twice and lied to me so much that I have decided to refuse to go back to her. 
As of a few days ago, she began threatening suicide. 
I have tirelessly spent these paat few days talking her out of it and she keeps hesitating because she wants to believe I'll come back. 
I know a lot of people will threaten this in order to get their way, but what happens if she really does? What do I do and how am I supposed to handle her death on my hands? I still love my wife but I cannot deal with getting cheated on again and constantly feeling insecure. 
I'm worried today may be the day she does it and I hope so much it doesn't happen.
Am I weird I don't get affected by compliments if it's coming from someone I know irl but I feel really good when internet strangers do it.
i need helpjust help me im crying so hard.
Ill probably suvive, they might not. Plus my life is meaningless and my future bleak, while they could cure cancer or something useful.
Sorry for wasting your time.
Honetly idkI dont know what im even doing here. I just feel like there is nothing and nowhere for me. 
All i can feel is either nothing or unbearably sad. Im ignoring friends every opitunity i can. 
I feel like im loosing my girlfriend. I only hurt everyone i talk too and i dont cause anything good. 
Im behind on my education, i feel alone but for the first time its not a feeling ive enjoyed. 
I have no hopes or dreams. 
I care about nothing, not family, not friends, not even my girlfriend.I would do something to end myself but i know im not strong and brave enough to do it, and knowing im that weak makes me sadder. 
The only thing i can do is push away all emotion and be empty, because as bad as it is im used to it, its my way of being normal."""

In [58]:
#integer encode text

tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded_data = tokenizer.texts_to_sequences([data])[0]
encoded_data

[58,
 18,
 31,
 32,
 59,
 1,
 60,
 4,
 18,
 14,
 19,
 20,
 7,
 61,
 33,
 15,
 10,
 62,
 2,
 63,
 3,
 10,
 21,
 34,
 35,
 1,
 22,
 64,
 3,
 65,
 3,
 66,
 36,
 3,
 23,
 24,
 16,
 25,
 37,
 38,
 67,
 7,
 68,
 31,
 32,
 1,
 22,
 69,
 70,
 71,
 72,
 37,
 38,
 73,
 23,
 74,
 16,
 6,
 2,
 7,
 75,
 76,
 20,
 7,
 77,
 3,
 78,
 79,
 80,
 36,
 1,
 17,
 25,
 81,
 16,
 82,
 83,
 84,
 85,
 86,
 87,
 3,
 39,
 88,
 40,
 11,
 26,
 89,
 41,
 7,
 42,
 43,
 26,
 8,
 1,
 8,
 2,
 90,
 44,
 1,
 91,
 3,
 92,
 23,
 93,
 15,
 4,
 94,
 1,
 95,
 96,
 4,
 18,
 11,
 1,
 97,
 98,
 99,
 100,
 33,
 15,
 101,
 2,
 102,
 45,
 103,
 104,
 105,
 106,
 107,
 46,
 27,
 108,
 7,
 43,
 6,
 2,
 1,
 109,
 21,
 34,
 6,
 110,
 111,
 44,
 1,
 112,
 1,
 113,
 39,
 114,
 115,
 116,
 41,
 117,
 118,
 119,
 120,
 1,
 17,
 121,
 11,
 1,
 12,
 42,
 19,
 122,
 123,
 124,
 8,
 6,
 1,
 125,
 126,
 127,
 10,
 5,
 128,
 21,
 129,
 130,
 131,
 132,
 47,
 133,
 9,
 134,
 4,
 135,
 13,
 136,
 2,
 4,
 137,
 138,
 139,
 47,
 140,
 141,
 142,
 28,

In [59]:
len(encoded_data)

359

In [60]:
vocab_size = len(tokenizer.word_index) + 1  # 0 reserved  for padding sequences
vocab_size

198

## To create a sequence of words to fit the model with one word as input and one as output

In [61]:
sequences = list()
for i in range(1,len(encoded_data)):
    sequence = encoded_data[i-1:i+1] # input,output word
    sequences.append(sequence)
print("Total Sequences:" , len(sequences))

Total Sequences: 358


In [62]:
sequences

[[58, 18],
 [18, 31],
 [31, 32],
 [32, 59],
 [59, 1],
 [1, 60],
 [60, 4],
 [4, 18],
 [18, 14],
 [14, 19],
 [19, 20],
 [20, 7],
 [7, 61],
 [61, 33],
 [33, 15],
 [15, 10],
 [10, 62],
 [62, 2],
 [2, 63],
 [63, 3],
 [3, 10],
 [10, 21],
 [21, 34],
 [34, 35],
 [35, 1],
 [1, 22],
 [22, 64],
 [64, 3],
 [3, 65],
 [65, 3],
 [3, 66],
 [66, 36],
 [36, 3],
 [3, 23],
 [23, 24],
 [24, 16],
 [16, 25],
 [25, 37],
 [37, 38],
 [38, 67],
 [67, 7],
 [7, 68],
 [68, 31],
 [31, 32],
 [32, 1],
 [1, 22],
 [22, 69],
 [69, 70],
 [70, 71],
 [71, 72],
 [72, 37],
 [37, 38],
 [38, 73],
 [73, 23],
 [23, 74],
 [74, 16],
 [16, 6],
 [6, 2],
 [2, 7],
 [7, 75],
 [75, 76],
 [76, 20],
 [20, 7],
 [7, 77],
 [77, 3],
 [3, 78],
 [78, 79],
 [79, 80],
 [80, 36],
 [36, 1],
 [1, 17],
 [17, 25],
 [25, 81],
 [81, 16],
 [16, 82],
 [82, 83],
 [83, 84],
 [84, 85],
 [85, 86],
 [86, 87],
 [87, 3],
 [3, 39],
 [39, 88],
 [88, 40],
 [40, 11],
 [11, 26],
 [26, 89],
 [89, 41],
 [41, 7],
 [7, 42],
 [42, 43],
 [43, 26],
 [26, 8],
 [8, 1],
 [1, 8]

In [63]:
#splitting the data
sequences = np.array(sequences)
x,y = sequences[:,0],sequences[:,1]

In [64]:
x[:5]

array([58, 18, 31, 32, 59])

In [65]:
y[:5]

array([18, 31, 32, 59,  1])

In [66]:
# one hot encode output

y = to_categorical(y , num_classes = vocab_size)
y[:1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]], dtype=float32)

In [81]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=1))
model.add(LSTM(100)) 
model.add(Dropout(0.3))
model.add(Flatten()) 
model.add(Dense(vocab_size , activation = 'softmax'))

In [82]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_13 (Embedding)    (None, 1, 10)             1980      
                                                                 
 lstm_16 (LSTM)              (None, 100)               44400     
                                                                 
 dropout_8 (Dropout)         (None, 100)               0         
                                                                 
 flatten (Flatten)           (None, 100)               0         
                                                                 
 dense_12 (Dense)            (None, 198)               19998     
                                                                 
Total params: 66,378
Trainable params: 66,378
Non-trainable params: 0
_________________________________________________________________


In [83]:
model.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics=['accuracy'])

In [84]:
model.fit(x,y,epochs=200)

Epoch 1/200
12/12 [==============================] - 4s 3ms/step - loss: 5.2875 - accuracy: 0.0447 
Epoch 2/200
12/12 [==============================] - 0s 3ms/step - loss: 5.2816 - accuracy: 0.0754
Epoch 3/200
12/12 [==============================] - 0s 3ms/step - loss: 5.2761 - accuracy: 0.0754
Epoch 4/200
12/12 [==============================] - 0s 3ms/step - loss: 5.2699 - accuracy: 0.0754
Epoch 5/200
12/12 [==============================] - 0s 3ms/step - loss: 5.2609 - accuracy: 0.0754
Epoch 6/200
12/12 [==============================] - 0s 3ms/step - loss: 5.2513 - accuracy: 0.0754
Epoch 7/200
12/12 [==============================] - 0s 3ms/step - loss: 5.2368 - accuracy: 0.0754
Epoch 8/200
12/12 [==============================] - 0s 3ms/step - loss: 5.2213 - accuracy: 0.0754
Epoch 9/200
12/12 [==============================] - 0s 3ms/step - loss: 5.1973 - accuracy: 0.0754
Epoch 10/200
12/12 [==============================] - 0s 4ms/step - loss: 5.1692 - accuracy: 0.0754
Epoch 11

12/12 [==============================] - 0s 4ms/step - loss: 2.2220 - accuracy: 0.4553
Epoch 84/200
12/12 [==============================] - 0s 4ms/step - loss: 2.2014 - accuracy: 0.4469
Epoch 85/200
12/12 [==============================] - 0s 6ms/step - loss: 2.1561 - accuracy: 0.4665
Epoch 86/200
12/12 [==============================] - 0s 5ms/step - loss: 2.1541 - accuracy: 0.4832
Epoch 87/200
12/12 [==============================] - 0s 4ms/step - loss: 2.1100 - accuracy: 0.4888
Epoch 88/200
12/12 [==============================] - 0s 4ms/step - loss: 2.1098 - accuracy: 0.4832
Epoch 89/200
12/12 [==============================] - 0s 4ms/step - loss: 2.0689 - accuracy: 0.4665
Epoch 90/200
12/12 [==============================] - 0s 4ms/step - loss: 2.0501 - accuracy: 0.4944
Epoch 91/200
12/12 [==============================] - 0s 4ms/step - loss: 2.0206 - accuracy: 0.5028
Epoch 92/200
12/12 [==============================] - 0s 4ms/step - loss: 1.9865 - accuracy: 0.5168
Epoch 93/200


12/12 [==============================] - 0s 6ms/step - loss: 1.1482 - accuracy: 0.5922
Epoch 165/200
12/12 [==============================] - 0s 4ms/step - loss: 1.1637 - accuracy: 0.5950
Epoch 166/200
12/12 [==============================] - 0s 6ms/step - loss: 1.1348 - accuracy: 0.5810
Epoch 167/200
12/12 [==============================] - 0s 4ms/step - loss: 1.1263 - accuracy: 0.6117
Epoch 168/200
12/12 [==============================] - 0s 4ms/step - loss: 1.1255 - accuracy: 0.6089
Epoch 169/200
12/12 [==============================] - 0s 4ms/step - loss: 1.1736 - accuracy: 0.5503
Epoch 170/200
12/12 [==============================] - 0s 6ms/step - loss: 1.1174 - accuracy: 0.5922
Epoch 171/200
12/12 [==============================] - 0s 4ms/step - loss: 1.1034 - accuracy: 0.6061
Epoch 172/200
12/12 [==============================] - 0s 6ms/step - loss: 1.1140 - accuracy: 0.5698
Epoch 173/200
12/12 [==============================] - 0s 6ms/step - loss: 1.1229 - accuracy: 0.5922
Epoc

In [85]:
loss,accuracy = model.evaluate(x,y)

12/12 [==============================] - 1s 1ms/step - loss: 0.9950 - accuracy: 0.5978


# Predictive System

In [86]:
def gen_seq(model,tokenizer,enter_text,n_pred):
    in_text,result = enter_text,enter_text
    for _ in range(n_pred):
        
        encoded = tokenizer.texts_to_sequences([in_text])[0]
        encoded = np.array(encoded)
        
        predict_yhat=model.predict(encoded) 
        yhat=np.argmax(predict_yhat)
        out_word=''
        for word, index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
        in_text,result = out_word,result + " " + out_word
    return result



In [87]:
gen_seq(model,tokenizer,'Threatening',2)

1/1 [==============================] - 0s 96ms/step


'Threatening suicide i'

In [93]:
gen_seq(model,tokenizer,'care',10)

1/1 [==============================] - 0s 16ms/step


'care about nothing not even my wife for good because she'